# Generated by Django 3.0.4 on 2021-12-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0006_auto_20200315_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='sol_name',
        ),
    ]
